version: '3.8'
services:    
    mongo:
        image: mongo:6.0.2
        volumes:
            - mongo_data:/data/db
        ports:
            - 27017:27017
        env_file:
            - ./.env
        restart: unless-stopped
    
    frontend:
        user: $UID:$GID
        build:
            context: ./frontend
            target: base
        volumes:
        - ./frontend:/frontend
        env_file:
            - ./.env
        entrypoint: /frontend/entrypoint.sh
        ports:
          - 3000:3000
    
    backend:
        build: ./backend
        env_file:
            - ./.env
        ports:
            - 80:80
        volumes:
            - ./backend:/app
        tty: true
        depends_on:
            - mongo

volumes:
    mongo_data:
